#!/bin/bash
cd $1
echo "<===="`date`"======>" >> gitlogfile.txt 
git add .
git commit >> gitlogfile.txt 
echo "</==="`date`"======>" >> gitlogfile.txt 
notify-send "git commit:" "finished."
gvim -f gitlogfile.txt

